-- first.sql
-- Run this in the Supabase SQL Editor to set up all required tables and constraints.

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS users (
    usn TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    phone_number TEXT,
    name TEXT NOT NULL,
    department TEXT NOT NULL,
    year TEXT NOT NULL,
    bio TEXT,
    profile_picture TEXT,
    cover_image TEXT,
    social_links JSONB DEFAULT '{}'::jsonb,
    password_hash TEXT NOT NULL,
    role TEXT DEFAULT 'student',
    status TEXT DEFAULT 'active',
    is_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Posts Table
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usn TEXT REFERENCES users(usn) ON DELETE CASCADE NOT NULL,
    caption TEXT,
    category TEXT NOT NULL,
    media_url TEXT NOT NULL,
    media_type TEXT DEFAULT 'image',
    status TEXT DEFAULT 'pending',
    rejection_reason TEXT,
    is_featured BOOLEAN DEFAULT false,
    likes_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    talent_score INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for speedy timeline fetches
CREATE INDEX IF NOT EXISTS idx_posts_usn ON posts(usn);
CREATE INDEX IF NOT EXISTS idx_posts_status ON posts(status);

-- 3. Create Likes Table (Likes/Dislikes)
CREATE TABLE IF NOT EXISTS likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    usn TEXT REFERENCES users(usn) ON DELETE CASCADE NOT NULL,
    type TEXT DEFAULT 'like',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index to avoid repeat clicks and speed up reactions query
CREATE UNIQUE INDEX IF NOT EXISTS idx_likes_unique ON likes(post_id, usn) WHERE post_id IS NOT NULL;

-- 4. Create Comments Table
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    usn TEXT REFERENCES users(usn) ON DELETE CASCADE NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_comments_post_id ON comments(post_id);

-- 5. Create Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usn TEXT REFERENCES users(usn) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT NOT NULL,
    read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_usn_read ON notifications(usn, read);

-- ==========================================
-- OPTIONAL INITIAL SEED DATA
-- ==========================================

-- Insert Default Dean / Admin
INSERT INTO users (usn, username, phone_number, name, department, year, bio, profile_picture, cover_image, password_hash, role, status, is_verified)
VALUES (
    'ADMIN001',
    'dean',
    '+919876543213',
    'Dean Of Student Affairs',
    'Administration',
    'Faculty',
    'University Talent Moderator. Empowering students to express and excel.',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    'https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&q=80&w=1000',
    'admin123',
    'admin',
    'active',
    true
) ON CONFLICT (usn) DO NOTHING;

-- Insert Rohit student
INSERT INTO users (usn, username, phone_number, name, department, year, bio, profile_picture, cover_image, password_hash, role, status, is_verified)
VALUES (
    '1RV22CS001',
    'rohit',
    '+919876543210',
    'Rohit Sharma',
    'Computer Science',
    '3rd Year',
    'Full Stack Engineer & AI enthusiast. Building decentralized platforms. Hackathon winner 2026.',
    'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=200',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1000',
    'student123',
    'student',
    'active',
    true
) ON CONFLICT (usn) DO NOTHING;
